pipeline {
   agent any

   stages {
      
      stage('Newman Tests') {
         steps {            
            sh '''            
            cd api/newman
            newman run Examen.postman_collection.json -e HerokuDiego.postman_environment.json
            '''            
         }        
      }
      
        stage('Jmeter Tests') {
         steps {            
            sh '''            
            cd load
            export PATH=/home/pjcalvov/jmeter/apache-jmeter-5.3/bin:$PATH
            jmeter -n -t examen_test_plan_diego.jmx
            '''            
         }         
      }

      stage('RestAssured Tests') {
         steps {            
            sh '''            
            cd api/restassured
            mvn clean test            
            '''            
         }        
      }

   }
}
