pipeline {
   agent any

   stages {
      stage('Newman Tests') {
         steps {            
            sh '''            
            cd api/newman
            newman run Examen.postman_collection.json -e HerokuDiego.postman_environment.json
            '''
            // To run Maven on a Windows agent, use
            // bat "mvn -Dmaven.test.failure.ignore=true clean package"
            
         }

        
      }
   }
}
