pipeline {
   agent any

   stages {
      
      stage('Newman Tests') {
         steps {            
            sh '''            
            cd api/newman
            newman run Examen.postman_collection.json -e HerokuDiego.postman_environment.json
            '''            
         }        
      }
      
        stage('Jmeter Tests') {
         steps {            
            sh '''            
            cd load
            export PATH=/home/pjcalvov/jmeter/apache-jmeter-5.3/bin:$PATH
            jmeter -n -t examen_test_plan_diego.jmx
            '''            
         }         
      }

      stage('RestAssured Tests') {
         steps {            
            sh '''            
            cd api/restassured
            mvn clean test            
            '''            
         }        
      }

   }

   environment {
        EMAIL_TO = 'die14@hotmail.com'
    }
   post {
        failure {
            emailext body: 'Check console output at $BUILD_URL to view the results. \n\n ${CHANGES} \n\n -------------------------------------------------- \n${BUILD_LOG, maxLines=100, escapeHtml=false}', 
                    to: "${EMAIL_TO}", 
                    subject: 'Build failed in Jenkins: $PROJECT_NAME - #$BUILD_NUMBER'
        }
        unstable {
            emailext body: 'Check console output at $BUILD_URL to view the results. \n\n ${CHANGES} \n\n -------------------------------------------------- \n${BUILD_LOG, maxLines=100, escapeHtml=false}', 
                    to: "${EMAIL_TO}", 
                    subject: 'Unstable build in Jenkins: $PROJECT_NAME - #$BUILD_NUMBER'
        }
        changed {
            emailext body: 'Check console output at $BUILD_URL to view the results.', 
                    to: "${EMAIL_TO}", 
                    subject: 'Jenkins build is back to normal: $PROJECT_NAME - #$BUILD_NUMBER'
        }
    }
    
}
